#!/bin/bash

__BASE_DIR=$(dirname "$0")

# import functions definition
. $__BASE_DIR/lib/installer.sh

# debian packages
apt update && apt install \
    wget \
    curl \
    jq \
    gdebi \
    git \
    zsh \
    tilix \
    openjdk-11-jdk \
    python3 \
    python3-pip \
    apt-transport-https \
    ca-certificates \
    software-properties-common \
    lsb-release

# snap packages
snap install \
    mockoon \
    ngrok    

# SublimeText
SUBLIME_BINARY="sublime-text_build-4126_amd64.deb"
SUBLIME_URL="https://download.sublimetext.com/${SUBLIME_BINARY}"
SUBLIME_STATUS=$(deb_package_installed "sublime-text")

if [[ -z "${SUBLIME_STATUS}" ]]; then
    get_installer "${SUBLIME_URL}" "${SUBLIME_BINARY}"
    install_deb_package "${SUBLIME_BINARY}"
fi;

# VSCode
VSCODE_BINARY="code_1.68.1-1655263094_amd64.deb"
VSCODE_URL="https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"
VSCODE_STATUS=$(deb_package_installed "code")

if [[ -z "${VSCODE_STATUS}" ]]; then
    get_installer "${VSCODE_URL}" "${VSCODE_BINARY}"
    install_deb_package "${VSCODE_BINARY}"
fi;

# DBeaver
DBEAVER_BINARY="dbeaver-ce_latest_amd64.deb"
DBEAVER_URL="https://dbeaver.io/files/${DBEAVER_BINARY}"
DBEAVER_STATUS=$(deb_package_installed "dbeaver-ce")

if [[ -z "${DBEAVER_STATUS}" ]]; then
    get_installer "${DBEAVER_URL}" "${DBEAVER_BINARY}"
    install_deb_package "${DBEAVER_BINARY}"
fi;

# Docker
DOCKER_STATUS=$(deb_package_installed "docker-ce")

if [[ -z "${DOCKER_STATUS}" ]]; then
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    apt update && apt install docker-ce
fi;    

# clean up
delete_temp_files
