#!/bin/bash

# foreground colors
readonly FG_COLOR_DEFAULT="39"
readonly FG_COLOR_BLACK="30"
readonly FG_COLOR_RED="31"
readonly FG_COLOR_GREEN="32"
readonly FG_COLOR_YELLOW="33"
readonly FG_COLOR_BLUE="34"
readonly FG_COLOR_MAGENTA="35"
readonly FG_COLOR_CYAN="36"
readonly FG_COLOR_LIGHT_GRAY="37"
readonly FG_COLOR_DARK_GRAY="90"
readonly FG_COLOR_LIGHT_RED="91"
readonly FG_COLOR_LIGHT_GREEN="92"
readonly FG_COLOR_LIGHT_YELLOW="93"
readonly FG_COLOR_LIGHT_BLUE="94"
readonly FG_COLOR_LIGHT_MAGENTA="95"
readonly FG_COLOR_LIGHT_CYAN="96"
readonly FG_COLOR_WHITE="97"

# background colors
readonly BG_COLOR_DEFAULT="49"
readonly BG_COLOR_BLACK="40"
readonly BG_COLOR_RED="41"
readonly BG_COLOR_GREEN="42"
readonly BG_COLOR_YELLOW="43"
readonly BG_COLOR_BLUE="44"
readonly BG_COLOR_MAGENTA="45"
readonly BG_COLOR_CYAN="46"
readonly BG_COLOR_LIGHT_GRAY="47"
readonly BG_COLOR_DARK_GRAY="100"
readonly BG_COLOR_LIGHT_RED="101"
readonly BG_COLOR_LIGHT_GREEN="102"
readonly BG_COLOR_LIGHT_YELLOW="103"
readonly BG_COLOR_LIGHT_BLUE="104"
readonly BG_COLOR_LIGHT_MAGENTA="105"
readonly BG_COLOR_LIGHT_CYAN="106"
readonly BG_COLOR_WHITE="107"

readonly NORMAL="0"
readonly BOLD="1"
readonly DIM="2"
readonly ITALIC="3"
readonly UNDERLINED="4"
readonly BLINK="5"